// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7j7F6nDf54wiiloUWP854fs5XoQIbcCk',
    appId: '1:243381277021:web:29f9279b48ca1d100f58b4',
    messagingSenderId: '243381277021',
    projectId: 'reportnic-9942b',
    authDomain: 'reportnic-9942b.firebaseapp.com',
    storageBucket: 'reportnic-9942b.firebasestorage.app',
    measurementId: 'G-99743VE1DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_cliPXxxblnuJLPFXj5bheIZZY86tSXM',
    appId: '1:243381277021:android:4c4890b32d7c73d60f58b4',
    messagingSenderId: '243381277021',
    projectId: 'reportnic-9942b',
    storageBucket: 'reportnic-9942b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmdT0btInF28SxVhUV34Wb3-sUVBjmuEI',
    appId: '1:243381277021:ios:f66bb4e6c33863730f58b4',
    messagingSenderId: '243381277021',
    projectId: 'reportnic-9942b',
    storageBucket: 'reportnic-9942b.firebasestorage.app',
    iosBundleId: 'com.example.rptn01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmdT0btInF28SxVhUV34Wb3-sUVBjmuEI',
    appId: '1:243381277021:ios:f66bb4e6c33863730f58b4',
    messagingSenderId: '243381277021',
    projectId: 'reportnic-9942b',
    storageBucket: 'reportnic-9942b.firebasestorage.app',
    iosBundleId: 'com.example.rptn01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7j7F6nDf54wiiloUWP854fs5XoQIbcCk',
    appId: '1:243381277021:web:0d759f9b3f897ba30f58b4',
    messagingSenderId: '243381277021',
    projectId: 'reportnic-9942b',
    authDomain: 'reportnic-9942b.firebaseapp.com',
    storageBucket: 'reportnic-9942b.firebasestorage.app',
    measurementId: 'G-GQ8FL5MPHS',
  );
}
